version: '3.5'
services:
  db:
    image: postgres:15-bullseye
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "(bundle check || bundle install) && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - RAILS_ENV=development
  
  frontend:
    image: node:18
    command: bash -c "cd frontend && yarn install && yarn start"
    tty: true
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - web
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - PORT=3001



volumes:
  frontend:
  node_modules:
  postgres:
  
