version: '3.5'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    tty: true
    command: bash -c "(bundle check || bundle install) && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
  
  frontend:
    image: node:18
    command: bash -c "cd frontend && yarn && yarn start"
    tty: true
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - web
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - PORT=3001



volumes:
  frontend:
  node_modules:
  postgres:
